name:                monad-challenges-solutions
version:             0.1.0.0
github:              "ezoern/monad-challenges-solutions"
license:             BSD3
author:              "Eric Zoerner"
maintainer:          "eric.zoerner@nike.com"
copyright:           "2018 Eric Zoerner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/ezoern/monad-chal#readme>

dependencies:
- base >= 4.7 && < 5
- monad-challenges
- split

library:
  source-dirs: src

tests:
  monad-challenges-solutions-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - monad-challenges-solutions
